language: node_js
node_js:
  - "stable"

sudo: false

notifications:
  email: false

cache:
  directories:
    - node_modules
    - jspm_packages

branches:
  only:
    - master

install:
  - npm install
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - node_modules/.bin/jspm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run ci
